### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by FireLizard** [mrkschan/ctags-status#11]
Got this error on opening files...

Stack Trace:

```
Uncaught TypeError: Cannot read property 'replace' of undefined
  at parse (D:\Users\sgi\.atom\packages\ctags-status\lib\ctags.coffee:13:22)
  at D:\Users\sgi\.atom\packages\ctags-status\lib\ctags.coffee:19:13
  at Ctags.module.exports.Ctags.parseTags (D:\Users\sgi\.atom\packages\ctags-status\lib\ctags.coffee:33:9)
  at D:\Users\sgi\.atom\packages\ctags-status\lib\ctags.coffee:32:15
  at Socket.<anonymous> (D:\Users\sgi\AppData\Local\atom\app-0.196.0\resources\app.asar\src\buffered-process.js:85:13)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at Pipe.onread (net.js:517:20)
```

System:
- Win8.1 Pro 64bit
- Atom v0.196.0
- ctags-status v1.2.1

**Comment by mrkschan** [comment]
@FireLizard Do you know which kind of programming language the file contains that broke the plugin?

**Comment by FireLizard** [comment]
Its a php file

**Comment by mrkschan** [comment]
@FireLizard , i'm sorry i dont have a windows machine nearby, may need a few more days to work on this issue.

**Comment by mrkschan** [comment]
Hey @FireLizard, i guess the problem is not related to PHP / Windows. Are you using hard tabs in your PHP file for indentation?

**Comment by FireLizard** [comment]
No, I'm using soft tabs for my PHP files.
Today I got a similar error message: "Cannot read property 'split' of undefined".

**Comment by mrkschan** [comment]
@FireLizard do you try the latest version v1.2.3? I patched the parser there and see if it helps.

**Comment by mrkschan** [comment]
Hey @FireLizard please give v1.2.5 a try. I got a Windows machine and caught the same error. Thx for reporting :)

**Comment by FireLizard** [comment]
Yeah now it works! =)
Thank you @mrkschan for your effort.
