### ISSUE TITLE
OS X 10.10.2 - Only works when Atom started from terminal

### ISSUE THREAD

**Issue by Michael-Thibault** [mrkschan/ctags-status#29]
Rather simple problem but no idea about the cause.

When I start Atom from the shell using `atom` , ctags-status works without issue. However, when I start Atom by clicking its icon on the dock, all it displays is `[global]` , no matter the actual scope. This was tested by opening the same project file, and disabling all packages except for core packages and ctags-status. This problem also occurs when Atom is launched by a double-click on the .app package. :confused: 

I don't mind the limitation terribly because there's an easy work-around, it'd just be nice if it worked without having to start it from the terminal all the time.

**Comment by mrkschan** [comment]
Would you mind to share me more info, like atom version, ctags-status plugin version, and if possible, anything you see in your atom's developer console (view > developer > toggle developer tools).

**Comment by Michael-Thibault** [comment]
**Atom:** 1.1.0
**ctags-status:** 1.3.3

As for the dev console, this is what I get for opening issues when I'm tired. Should've checked, didn't. So here's what will undoubtedly be handy:

First error, which happened once after starting Atom (not via terminal):

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ctags: illegal option -- -
usage: ctags [-BFadtuwvx] [-f tagsfile] file ...

/Users/mthibault/.atom/packages/ctags-status/lib/ctags.coffee:72
```

Second error, which each time I opened a new file. Doesn't happen while switching between open tabs though:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ctags: illegal option -- -
usage: ctags [-BFadtuwvx] [-f tagsfile] file ...

ctags.coffee:45
```

Now for errors when starting Atom via terminal. This one once when starting Atom:

```
ctags: Warning: Unknown language "Go:.go" in "langmap" option
ctags: Warning: unknown language "Go" in --regex-Go option
ctags: Warning: unknown language "Go" in --regex-Go option
ctags: Warning: unknown language "Go" in --regex-Go option

/Users/mthibault/.atom/packages/ctags-status/lib/ctags.coffee:72
```

The above error happens again, once each time a file is opened, but at ctags.coffee:45 .

XCode might be out-of-date, and if so, my bad. I'll update everything and get back to you.

**Comment by mrkschan** [comment]
I didn't really try install ctags from homebrew, did you do so? BTW, thx for the report.

**Comment by mrkschan** [comment]
BTW, can you send me the output of `which ctags` in a terminal?

**Comment by Michael-Thibault** [comment]
Yeah I used homebrew to install ctags.

Output of `which ctags` in terminal:

```
/usr/local/bin/ctags
```

**Comment by mrkschan** [comment]
So ... that means .... when you run atom from terminal, it uses the ctags installed via homebrew. If you run atom from the dock / UI, it uses ctags from xcode.

I think the $PATH environment variable is not configured properly... I will try to get a mac and debug this. Sorry for any inconvenience introduced to you.

**Comment by Michael-Thibault** [comment]
Meh, not really a huge inconvenience. Bugs happen, it's all good. :smile:

**Comment by Michael-Thibault** [comment]
Unfortunately updating to OS X 10.10.5 and Xcode 7.1 didn't fix it. Not that I really expected to. Oh well.

**Comment by mrkschan** [comment]
A simple fix is ... allow you to set the path to `ctags`. Would that work for u?

**Comment by mrkschan** [comment]
Hey @Michael-Thibault, could you try editing `/etc/paths` like http://stackoverflow.com/a/16409497/433662? If that works, I would just add that to the installation instructions for Mac.

**Comment by mrkschan** [comment]
Eh... it seems that putting /usr/local/bin/ there in `/etc/paths` is not a good practice. http://superuser.com/questions/324616/how-should-i-set-the-path-variable-on-my-mac-so-the-hombrew-installed-tools-are

**Comment by mrkschan** [comment]
@Michael-Thibault would you mind to give v1.3.4 a shot?

**Comment by Michael-Thibault** [comment]
> try editing /etc/paths like http://stackoverflow.com/a/16409497/433662? If that works, I would just add that to the installation instructions for Mac.

I had /usr/local/bin in there anyway, above /usr/bin. Whoops, thanks for pointing that out. Fixed. :smile:

> would you mind to give v1.3.4 a shot?

Didn't fix the bug, unfortunately.

**Comment by Michael-Thibault** [comment]
> Didn't fix the bug, unfortunately.

What am I saying. The update itself doesn't fix the bug, but the new ability to set a specific ctags to use does let me work around it.

**Comment by mrkschan** [comment]
thx for testing, dude.
