### ISSUE TITLE
SCSS doesn't appear to "climb the tree", only shows 1 level of selector

### ISSUE THREAD

**Issue by dmland** [mrkschan/ctags-status#34]
Given the following SCSS:

```
.root {
  .child {
    .grandchild {
      color: #CCCCCC;
    }
  }
}
```

When the cursor is on the color rule, ctags-status will report [.grandchild], not [.root > .child > .grandchild]. Is this the expected behavior? Is there a trick to make it "climb the tree" to show the full selector ancestry?

**Comment by mrkschan** [comment]
Did you select to option "Show outer scope(s)"?

**Comment by mrkschan** [comment]
![scss-ctags](https://cloud.githubusercontent.com/assets/118147/13942338/425d7b54-f02c-11e5-9cc1-7d2805b61436.png)

**Comment by dmland** [comment]
Thanks, but at this point, it just says "[global]" all the time, never changes at all. I'm not sure what I've done wrong, but as I was actually looking for a status-line display of the calculated scss selector at the insertion point, I'm not sure that ctags-status is the tool for me. Thank you for your help, but I think we can close this issue.

**Comment by mrkschan** [comment]
Hey @dmland, which OS are you using? And, did the [screencap](https://github.com/mrkschan/ctags-status/issues/34#issuecomment-199635766) above tell you if ctags-status really fits your use case?

**Comment by dmland** [comment]
I'm on Mac OS X 10.9.5.

The screencap suggests that it would go _part_ of the way to fitting my use case.

As long as we're discussing blue skies, ideally, a full implementation would be more like this (and I apologize for starting off with a too-simple example):

```
.root, .trunk {
  .child {
    .grandchild {
      color: #CCCCCC;
    }
  }
}
```

Would yield `[.root .child .grandchild, .trunk .child .grandchild]`

Two things are different from the current behavior:
1. no right-angle indicators of "climbing the hierarchy," because they have a very specific meaning in CSS
2. `.root, .trunk` generates two separate selectors. It's a tree with two roots, I guess.

Even as I write this, I realize that this is a big request: turning ctags-status into a real scss preprocessor. It's a lot more than just "climbing the tree," because of variables, the way the ampersand works (it acts like a variable for the parent selector).

**Comment by mrkschan** [comment]
Re 1: Good point. '>' doesn't make sense in CSS/SCSS/etc.
Re 2: Yes, ctags found two node on that line (`.root` and `.trunk`). 

CSS/SCSS/etc. support is still pretty beta to be honest. I am still looking at if ctags can work better with these languages.
