### ISSUE TITLE
Just shows "[global]" in the status bar

### ISSUE THREAD

**Issue by michaeldavidtodd** [mrkschan/ctags-status#46]
Hi, I just tried this out in Atom (1.28.0) using SCSS and it's not working for me. All it shows is `[global]` in the status bar, no matter what line in my SCSS I click on. I'm using all the default settings and also tried selecting "Show outer scope(s)".

I was excited to find this package because I use to have something similar (I think it may have been a part of the Emmet package I'm using). I used to be able to hover over any nested selector in my SCSS and it would show me the full compiled selector in in a tooltip. Sadly, it stopped working at some point and I have no idea what the feature was called. I've had the hardest time looking it up or finding alternatives until I came across your package from a StackOverflow answer. Hoping to get something working again.

**Comment by naaadz** [comment]
I have this problem too, any help?

**Comment by mrkschan** [comment]
Possibly the finder is hitting corner case…? https://github.com/mrkschan/ctags-status/blob/master/lib/scope-finder.coffee#L171

Could you post a minimal scss file that can reproduce the issue?
